### ISSUE TITLE
How to use replayId from Streaming API

### ISSUE THREAD

**Issue by CoolEsh** [advisors-excel-llc/salesforce-rest-sdk#33]
Hello,

I wish to use replayId from streaming API to get missing messages while listener was down. I found the following code 
`$replayExtension = new \AE\SalesforceRestSdk\Bayeux\Extension\ReplayExtension({replayId here});`
`$streamingClient->addExtension($replayExtension);`
But I can't get how to tie this to `$channel->subsribe` code. Could you point me to some piece of code which uses replayId to get messages that was not processed during listener shutdown?

Thanks

**Comment by curiosity26** [comment]
The Bayuex client takes care of it all for you. You only need to create the client, add the extensions you want, subscribe a consumer to a channel and then start the client.

Here's a quick example:

```php
<?php

$streamingClient = new BayeuxClient(
            new LongPollingTransport(),
            new OAuthProvider(
                getenv("SF_CLIENT_ID"),
                getenv("SF_CLIENT_SECRET"),
                getenv("SF_LOGIN_URL"),
                getenv("SF_USER"),
                getenv("SF_PASS")
            )
        );

$streamingClient->addExtension(new ReplayExtension(ReplayExtension::REPLAY_SAVED));

// Creates a new channel with the client if one does not exist already
$channel = $streamingClient->getChannel('/topic/Accounts');
// Subscribe a consumer to the channel
$channel->subscribe(
       Consumer::create(
            function (ChannelInterface $channel, Message $message) use ($name) {
                $data = $message->getData();
                $sobject = $data->getSobject();

                // Do something with the object

                $replayId = $data->getEvent()->getReplayId();
            }
      )
);

// When you start the client, all defined channels make a subscribe call to Salesforce after the handshake
// When the channel receives a message from Salesforce, all consumers that have subscribed
// to the channel are fired in order of their priority
// This will run forever or until you stop it
$streamingClient->start();

```

**Comment by RileyDavidson** [comment]
I have a similar question. If I want to manually specify the Replay ID, I seem to not able to do this. Can you advise? I assumed ` $channel->addExtension(new ReplayExtension(<REPLAY_ID_HERE>));` would work.
