### ISSUE TITLE
Issue regarding topic subscribing

### ISSUE THREAD

**Issue by ibirds-github** [advisors-excel-llc/salesforce-rest-sdk#47]
Hi All,
I am using your "ae/salesforce-rest-sdk" library. Its awesome. Thanks for it.

However i am trying to do Streaming api using this. But i am getting error. 

1) I created a push topic in my org , called "InvoiceStatementUpdates". 
2) I followed the instructions given on readme
3) When i run the code, it started listing
4) Then i opened my salesforce org and push a event on this topic by creating one contact
5) As soon as i created a contact my php page stopped and given below error.

( ! ) Fatal error: Uncaught TypeError: Argument 1 passed to {closure}() must implement interface AE\SalesforceRestSdk\Bayeux\ConsumerInterface, instance of AE\SalesforceRestSdk\Bayeux\Channel given in D:\wamp64\www\salesforce-rest\client.php on line 47
( ! ) TypeError: Argument 1 passed to {closure}() must implement interface AE\SalesforceRestSdk\Bayeux\ConsumerInterface, instance of AE\SalesforceRestSdk\Bayeux\Channel given in D:\wamp64\www\salesforce-rest\client.php on line 47

Please help me to solve this. I have attached my code as well as error screen.

```
<?php
use AE\SalesforceRestSdk\Bayeux\BayeuxClient;
use AE\SalesforceRestSdk\AuthProvider\OAuthProvider;
use AE\SalesforceRestSdk\Bayeux\Transport\LongPollingTransport;
use Doctrine\Common\Annotations\AnnotationRegistry;
use AE\SalesforceRestSdk\Bayeux\Consumer;
use AE\SalesforceRestSdk\Bayeux\ConsumerInterface;
use AE\SalesforceRestSdk\Bayeux\Message;
use AE\SalesforceRestSdk\Bayeux\Extension\ReplayExtension;
use AE\SalesforceRestSdk\Bayeux\Extension\CachedReplayExtension;
use Symfony\Component\Cache\Adapter\FilesystemAdapter;

$loader = require_once 'vendor/autoload.php';
AnnotationRegistry::registerLoader(array($loader, "loadClass"));


$client = new BayeuxClient(
      new LongPollingTransport(),
      new OAuthProvider(
     "xxxxxx",
      "yyyyyyy",
      "https://login.salesforce.com",
      "ttttt",
      "zzzzz"
  )
 );



/** @var BayeuxClient $client */

// Getting a channel tells the client you want to subscribe to a topic
$channel = $client->getChannel('/topic/InvoiceStatementUpdates');

// Give some durability to the messages on this channel by adding the ReplayExtension
$channel->addExtension(new ReplayExtension(ReplayExtension::REPLAY_SAVED));

// Using the CachedReplayExtension give greater durability in that it will remember the replay Id of the last
// message received and pick up where it left off, even if the process stops and restarts. If no messages for the
// channel topic have been received, it will use the value provided in the constructor.
// Again, Any Psr\Cache\CacheItemPoolInterface will do for the adapter parameter
$channel->addExtension(new CachedReplayExtension(new FilesystemAdapter(), CachedReplayExtension::REPLAY_SAVED));


// Register topic consumers prior to starting the client
$channel->subscribe(
    Consumer::create(function (ConsumerInterface $consumer, Message $message) {
        // This will be fired when the client receives a topic notification
        
        $payload = $message->getData();
        
        // The payload has information about the event that occurred
        $event = $payload->getEvent();
        
        echo $event->getType(); // "created", "updated", "undeleted", "deleted"
        echo $event->getCreatedDate()->format(\DATE_ISO8601); // outputs the datetime the event was created
        echo $event->getReplayId(); // This ia n ID used by the replay extension so it can pick up the feed where it left off
        
        $sobject = $payload->getSobject();
        
        echo $sobject->Id; // Get the Id
        echo $sobject->getFields(); // this outputs all the fields and their values that were in the create or update request
    })
);

// Start the client to begin receiving notifications;
$client->start();

?>
```

By the way, one more thing, i wanted to subscibe "Platform Events" as well. Will this is also same as subscribing "Topic" ?

**Comment by curiosity26** [comment]
Thank you for bringing this to my attention, this is an error in the documentation. I apologize.

The Consumer::create() method takes a ChannelInterface parameter, not a ConsumerInterface.

`use AE\SalesforceRestSdk\Bayeux\ChannelInterface;` is the full namespace.

The documentation has been updated.

As for Platform Events, they are subscribed in the same way. Actually everything subscribes in the same way, the difference is the channel name. For Plaform Events, you'll use `/event/MY_PLATFORM_EVENT__e`, if you happen to be using the new Change Data Capture feature, then the channel name is something like `/data/AccountChangeEvent` or for a custom object `/data/Custom_Object__ChangeEvent`.

Generic events use the prefix `/u/` and when subscribing to a generic event from the client, the generic event is automatically created when subscribed to (if that setting is enabled in your SF org).
So for a generic event, the channel name might be `/u/MyCoolChannel`.

**Comment by ibirds-github** [comment]
Thanks, Its working now :)
