### ISSUE TITLE
having trouble autoloading JMS package

### ISSUE THREAD

**Issue by Satish2308** [advisors-excel-llc/salesforce-rest-sdk#49]
Doctrine\Common\Annotations\AnnotationException::semanticalError("The annotation "@JMS\Serializer\Annotation\ExclusionPolicy" in class AE\SalesforceRestSdk\Bayeux\Message does not exist, or could not be auto-loaded.")

This is the problem im facing while using this package. Im trying to implement in laraval. im trying to do pushTopic streaming from salesforce but for some reason it is not supporting.

**Comment by curiosity26** [comment]
You have to register the Autoloader when Laravel boots. I'm not super familiar with how Laravel bootstraps, but you could just do it in the index.php. See https://github.com/advisors-excel-llc/salesforce-rest-sdk#composer-autoloading-without-a-framework

**Comment by mark-jones-entanet** [comment]
Sorry, we should have updated this ticket when we found the solution. We used this package:

https://packagist.org/packages/indigophp/doctrine-annotation-autoload

to resolve this issue.

**Comment by gohelkiran30** [comment]
It's not mentioned anywhere in doc to use doctrine annotation package.
is it really required, if so than better to specify this in document itself...
