### ISSUE TITLE
Manually specify the Replay ID

### ISSUE THREAD

**Issue by RileyDavidson** [advisors-excel-llc/salesforce-rest-sdk#54]
If I want to manually specify the Replay ID, I seem to not able to do this. Can you advise? I assumed ` $channel->addExtension(new ReplayExtension(<REPLAY_ID_HERE>));` would work.

_Originally posted by @RileyDavidson in https://github.com/advisors-excel-llc/salesforce-rest-sdk/issues/33#issuecomment-506540801_

**Comment by curiosity26** [comment]
Hi @RileyDavidson, sorry for the late reply. Getting back to this now.

The parameter supplied in the constructor is only used as a default. Once the ReplayExtension starts processing methods, the values vary widely per each channel.

I've made an update to allow you to set the Replay ID for a specific channel by using:

```php
<?php

$ext = new ReplayExtension(ReplayExtension::REPLAY_NEWEST);
$ext->setReplayIdForChannel('/data/AccountChangeEvent', 841);

$channel->addExtension($ext);
```

Let me know if you have any further issues.

Thanks
Alex
